[project]
name = "gwsproto"
version = "0.1.0.dev1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andrew Schweitzer", email = "schweitz72@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "gridworks-protocol>=1.2.9",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
