linters:
  flake8:
    python: 3
    ignore: 'W28, W503, E722'
    max-line-length: 120
    max-complexity: 10
    fixer: true
fixers:
  enable: true
files:
  ignore:
    - 'DerivationTools/*'
    - 'gw_spaceheat/schema/*'
    - 'gw_spaceheat/data_classes/components/*'
    - 'gw_spaceheat/data_classes/cacs/*'
