"""layout generation command-line interface."""
from typing import Annotated

import typer
from pathlib import Path

import show_layout
from layout_gen.fixture_layouts import make_house0_fixture_layout

app = typer.Typer(
    no_args_is_help=True,
    pretty_exceptions_enable=False,
    rich_markup_mode="rich",
    help="GridWorks hardware layout tools.",
)

@app.command()
def mktest(
    layout: str = "house0",
    tag: str = "",
    write: bool = True,
    src: Path | None = None,
) -> None:
    """Generate the hardware layout file used by tests. (The nolan fixture
    is generated by the sema-native gen in tlayouts, not here.)"""
    if layout != "house0":
        raise typer.BadParameter(
            "layout must be 'house0' (the nolan fixture comes from tlayouts)"
        )

    working_output_dir = Path(__file__).parent.joinpath("output").resolve()
    working_output_dir.mkdir(exist_ok=True)
    config_output_path = Path(f"tests/config/{layout}-layout.json").resolve()
    if src is None:
        src_path = config_output_path
        if not src_path.exists():
            raise typer.BadParameter(
                f"{config_output_path} does not exist; pass --src to bootstrap from another layout file."
            )
    else:
        src_path = src.resolve()

    db = make_house0_fixture_layout(src_path)
    if write:
        db.write(config_output_path)
    if not tag:
        tag = layout
    working_path = working_output_dir.joinpath(f"{tag}.generated.json")
    db.write(working_path)
    show_layout.main(["-l", str(working_path)])
    print(".")

@app.command()
def show(
    env_file: str = ".env",
    layout_file: Annotated[
        str, typer.Option(
            "--layout-file", "-l",
            help=(
                "Name of layout file (e.g. hardware-layout.json or apple for apple.json). "
                "If path is relative it will be relative to settings.paths.config_dir. "
                "If path has no extension, .json will be assumed. "
                "If not specified default settings.paths.hardware_layout will be used."
            ),
        )
    ] = "",
    raise_errors: Annotated[
        bool, typer.Option(
            "--raise-errors",
            "-r",
            help="Raise any errors immediately to see full call stack."
        )
    ] = False,
    verbose: Annotated[
        bool, typer.Option(
            "--verbose",
            "-v",
            help="Print additional information"
        )
    ] = False,
    table_only: Annotated[
        bool, typer.Option(
            "--table-only",
            "-t",
            help="Print only the table"
        )
    ] = False,
):
    """Show hardware layout."""
    args = ["-e", env_file]
    if layout_file:
        args.extend(["-l", layout_file])
    if raise_errors:
        args.append("-r")
    if verbose:
        args.append("-v")
    if table_only:
        args.append("-t")
    show_layout.main(args)

@app.callback()
def _main() -> None: ...


# For sphinx:
typer_click_object = typer.main.get_command(app)

if __name__ == "__main__":
    app()
